//----------------------------------------------------------------------
// HWCtrl_Zynq.c:
//   Hardware access layer for Zynq PS running bare-metal or FreeRTOS.
//   The gnss_top_axi AXI4-Lite slave is memory-mapped into the PS
//   address space via the GP0 (or GP1) AXI master port.
//
//   Set GNSS_BASE_ADDR to the base address assigned in Vivado
//   Address Editor for the gnss_top_axi peripheral.
//   Default Vivado assignment for GP0 peripherals: 0x4000_0000+
//
// MAX2771 SPI wiring (PS SPI0 via MIO or EMIO):
//   PS SPI0 SCLK  -> MAX2771 SCLK
//   PS SPI0 MOSI  -> MAX2771 SDATA  (write path)
//   PS SPI0 MISO  <- MAX2771 SDATA  (read path; for config-only omit)
//   PS SPI0 SS0   -> MAX2771 CS_N
//   Tie the MAX2771 SHDN pin low (active) to keep the chip powered.
//
// MAX2771 SPI protocol:
//   32-bit transaction, MSB first, CPOL=0 CPHA=0 (SPI Mode 0).
//   Bits [31:28] = 4-bit register address.
//   Bits [27:0]  = 28-bit register data.
//----------------------------------------------------------------------

#include "HWCtrl.h"
#include "PlatformCtrl.h"
#include "xscugic.h"
#include "xspips.h"
#include "xil_io.h"
#include "xparameters.h"

// --------------- GNSS baseband address ---------------
// Match the base address shown in Vivado IP Integrator Address Editor.
#define GNSS_BASE_ADDR  0x43C00000UL

// PL-to-PS interrupt: IRQ_F2P[0] = GIC ID 61.
// Verify this in your Vivado design. Change if wired to a different line.
#define GNSS_IRQ_ID     61

// --------------- MAX2771 SPI ---------------
// PS SPI0 device ID from xparameters.h (generated by Vivado / SDK).
// Change to XPAR_XSPIPS_1_DEVICE_ID if using SPI1.
#define MAX2771_SPI_ID  XPAR_XSPIPS_0_DEVICE_ID

// SPI clock prescaler: PCLK / (2 * (prescaler+1)).
// With PCLK = 100 MHz and prescaler = 4, SCLK = 10 MHz.
// MAX2771 supports up to ~10 MHz SCLK.
#define MAX2771_SPI_PRESCALER  XSPIPS_CLK_PRESCALE_8  // 100MHz/8 = 12.5MHz; use 16 for 6.25MHz

// --------------- MAX2771 register addresses ---------------
#define MAX2771_REG_CONF1    0x0
#define MAX2771_REG_CONF2    0x1
#define MAX2771_REG_CONF3    0x2
#define MAX2771_REG_PLLCONF  0x3
#define MAX2771_REG_DIV      0x4
#define MAX2771_REG_FDIV     0x5
#define MAX2771_REG_STRM     0x6
#define MAX2771_REG_CLK      0x7

// --------------- MAX2771 register values for GPS L1CA ---------------
// Reference crystal: 16.368 MHz (standard GNSS reference)
// RF input: GPS L1 (1575.42 MHz)
// IF output: ~4.092 MHz
// CLKOUT (adc_clk): 16.368 MHz (= XTAL, bypassed through CLK register)
// Sample format: 2-bit I + 2-bit Q (sign + magnitude), 16.368 MSps
//
// These values are derived from the MAX2771 datasheet and EV kit guide.
// Verify against your specific board schematic.
// ---------------------
//
// CONF1 [27:0]:
//   [27:26] FCENX  = 0b11 : center frequency offset = +3 (fine tune)
//   [25:16] FCEN   = 0x60 : 4.092 MHz IF (FCEN * Fxtal/1023 ~ 4.092 MHz)
//   [15:12] F3OR5  = 0xF  : 5th order Butterworth filter
//   [11:8]  FGAIN  = 0x0  : filter gain = 0 dB
//   [7:4]   B1     = 0x0  : analog gain stage 1
//   [3:0]   MIXPOLE= 0xA  : mixer pole setting
//
// For a 16.368 MHz crystal, FCEN = 96d = 0x60 gives
// IF = 96 * 16.368MHz / 1023 ≈ 1.537 MHz (not 4.092 MHz).
// The actual formula depends on the filter configuration (F3OR5).
// Consult MAX2771 datasheet Table 2 for exact FCEN selection.
// The values below are from the Maxim reference design for GPS L1 only.
// --------------------

// CONF1: LNA, mixer, IF filter enabled; 4.092 MHz IF center
#define MAX2771_CONF1_VAL   0x0A4912A3UL

// CONF2: 2-bit output (sign+mag), I+Q enabled, 16.368 MSps output rate
//   [27:24] DIEID    = 0x0
//   [23]    BITS     = 0  : 1-bit quantization (set 1 for 2-bit)
//   [22]    FORMAT   = 0  : unsigned binary (set 1 for two's complement)
//   [21:18] GAINREF  = ...
//   [3:2]   IQEN     = 0b11 : I and Q enabled
//   [1:0]   ANAIQDIV = 0b00 : no divider
// For 2-bit sign/magnitude: BITS=1 (2 bits), FORMAT=0 (sign/mag)
#define MAX2771_CONF2_VAL   0x085F4002UL

// CONF3: default gain / filter passband settings
#define MAX2771_CONF3_VAL   0xEAFF1D2FUL

// PLLCONF: Integer-N PLL for 1575.42 MHz
//   With 16.368 MHz reference: N = 1575.42/16.368 = 96.25...
//   Use integer N=96, then fractional tune via FDIV.
//   [27]    PWRSAV  = 0 : PLL powered
//   [26:16] INT_PLL = 96 (0x60) when FRAC=0
#define MAX2771_PLLCONF_VAL 0x9EC0008BUL

// DIV: N divider = 96 for 1575.42 MHz
//   [27:21] RDIV   = 1 (reference divider)
//   [20:13] NDIV   = 96
//   [12:0]  FDIV_L = fractional lower part (0 for integer-N)
#define MAX2771_DIV_VAL     0x0C0D3000UL

// FDIV: fractional divider upper part (0 for integer-N)
#define MAX2771_FDIV_VAL    0x80000005UL

// STRM: streaming interface not used
#define MAX2771_STRM_VAL    0x00000000UL

// CLK: CLKOUT = XTAL (16.368 MHz), enable CLKOUT
//   [27] CLKOUT_SEL = 0 : CLKOUT follows XTAL
//   [26] L_CNT      = value for CLKOUT divider
//   [3]  CLKOUT_EN  = 1 : enable CLKOUT pin
#define MAX2771_CLK_VAL     0x10000000UL

static XScuGic   gic_inst;
static XSpiPs    spi_inst;
static DebugFunction DebugFunc = NULL;

// ----------------------------------------------------------------
// Internal: write one 32-bit word to MAX2771 over SPI
// ----------------------------------------------------------------
static void max2771_write_reg(u8 reg_addr, u32 data28)
{
    // Pack: bits[31:28] = address, bits[27:0] = data
    u32 packet = ((u32)(reg_addr & 0xF) << 28) | (data28 & 0x0FFFFFFFUL);
    u8 tx[4], rx[4];
    tx[0] = (packet >> 24) & 0xFF;
    tx[1] = (packet >> 16) & 0xFF;
    tx[2] = (packet >>  8) & 0xFF;
    tx[3] = (packet      ) & 0xFF;

    // Assert CS, transfer 4 bytes, deassert CS
    XSpiPs_SetSlaveSelect(&spi_inst, 0x0E);  // SS0 active (active-low bit mask)
    XSpiPs_PolledTransfer(&spi_inst, tx, rx, 4);
    XSpiPs_SetSlaveSelect(&spi_inst, 0x0F);  // deassert all SS
}

// ----------------------------------------------------------------
// Configure MAX2771 for GPS L1CA reception
// ----------------------------------------------------------------
static void max2771_init_gps_l1(void)
{
    // Order matters: configure PLL first, then analog chain, then output
    max2771_write_reg(MAX2771_REG_PLLCONF, MAX2771_PLLCONF_VAL);
    max2771_write_reg(MAX2771_REG_DIV,     MAX2771_DIV_VAL    );
    max2771_write_reg(MAX2771_REG_FDIV,    MAX2771_FDIV_VAL   );
    max2771_write_reg(MAX2771_REG_CLK,     MAX2771_CLK_VAL    );
    max2771_write_reg(MAX2771_REG_CONF3,   MAX2771_CONF3_VAL  );
    max2771_write_reg(MAX2771_REG_CONF2,   MAX2771_CONF2_VAL  );
    max2771_write_reg(MAX2771_REG_CONF1,   MAX2771_CONF1_VAL  );
    max2771_write_reg(MAX2771_REG_STRM,    MAX2771_STRM_VAL   );
}

// ================================================================
// Public API (implements HWCtrl.h interface)
// ================================================================

void AttachBasebandISR(InterruptFunction ISR)
{
    XScuGic_Config *cfg = XScuGic_LookupConfig(XPAR_SCUGIC_0_DEVICE_ID);
    XScuGic_CfgInitialize(&gic_inst, cfg, cfg->CpuBaseAddress);

    XScuGic_Connect(&gic_inst, GNSS_IRQ_ID,
                    (Xil_InterruptHandler)ISR, NULL);
    XScuGic_Enable(&gic_inst, GNSS_IRQ_ID);

    Xil_ExceptionRegisterHandler(XIL_EXCEPTION_ID_INT,
                                 (Xil_ExceptionHandler)XScuGic_InterruptHandler,
                                 &gic_inst);
    Xil_ExceptionEnable();
}

void AttachDebugFunc(DebugFunction Function)
{
    DebugFunc = Function;
}

// Address is DWORD offset (as used throughout gnss_top firmware).
U32 GetRegValue(int Address)
{
    return Xil_In32(GNSS_BASE_ADDR + ((u32)Address << 2));
}

void SetRegValue(int Address, U32 Value)
{
    Xil_Out32(GNSS_BASE_ADDR + ((u32)Address << 2), Value);
}

void LoadMemory(U32 *DestAddr, U32 *BasebandAddr, int Size)
{
    int i;
    for (i = 0; i < Size; i += 4)
        DestAddr[i >> 2] = Xil_In32(GNSS_BASE_ADDR + (u32)BasebandAddr + i);
}

void SaveMemory(U32 *BasebandAddr, U32 *SrcAddr, int Size)
{
    int i;
    for (i = 0; i < Size; i += 4)
        Xil_Out32(GNSS_BASE_ADDR + (u32)BasebandAddr + i, SrcAddr[i >> 2]);
}

void SetInputFile(char *FileName) {}

// Initialize PS SPI0 and configure MAX2771 for GPS L1CA.
// Call this once during system startup, before enabling the GNSS baseband.
void EnableRF(void)
{
    XSpiPs_Config *spi_cfg;
    int status;

    // Initialize PS SPI0
    spi_cfg = XSpiPs_LookupConfig(MAX2771_SPI_ID);
    if (!spi_cfg) return;

    status = XSpiPs_CfgInitialize(&spi_inst, spi_cfg, spi_cfg->BaseAddress);
    if (status != XST_SUCCESS) return;

    XSpiPs_Reset(&spi_inst);

    // Master mode, no auto-CS (we drive SS manually), CPOL=0 CPHA=0
    XSpiPs_SetOptions(&spi_inst,
        XSPIPS_MASTER_OPTION          |
        XSPIPS_FORCE_SSELECT_OPTION   |
        XSPIPS_CLK_ACTIVE_LOW_OPTION * 0 |  // CPOL=0
        XSPIPS_CLK_PHASE_1_OPTION    * 0    // CPHA=0 (data sampled on rising edge)
    );

    XSpiPs_SetClkPrescaler(&spi_inst, MAX2771_SPI_PRESCALER);

    // Deassert all chip selects initially
    XSpiPs_SetSlaveSelect(&spi_inst, 0x0F);

    // Configure MAX2771
    max2771_init_gps_l1();
}
