//----------------------------------------------------------------------
// HWCtrl_Zynq.c:
//   Hardware access layer for Zynq PS running FreeRTOS.
//   The gnss_top_axi AXI4-Lite slave is memory-mapped into the PS
//   address space via the GP0 AXI master port.
//
//   Set GNSS_BASE_ADDR to the base address assigned in Vivado
//   Address Editor for the gnss_top_axi peripheral.
//   Default assignment: 0x43C0_0000 (64 KB, set in bd_gnss_zynq.tcl).
//
// MAX2771 SPI wiring (PS SPI0 via EMIO on JB pmod):
//   JB Pin2 W8  -> MAX2771 SCLK
//   JB Pin1 V8  -> MAX2771 SDATA (MOSI)
//   JB Pin4 V7  -> MAX2771 /CS_A  (chip A)
//
// MAX2771 SPI protocol (48-bit transaction, MSB first):
//   Bits [47:36] = 12-bit register address (bits 11:4 always 0 for reg 0-10)
//   Bit  [35]    = 0 (write) / 1 (read)
//   Bits [34:32] = 000 (padding)
//   Bits [31:0]  = 32-bit register data
//
// Register configuration (24 MHz crystal, chip A):
//   F_LO   = 1572.420 MHz  ->  IF = 3.0 MHz below GPS L1
//   F_ADC  = 12.000 MHz    ->  12 MSps
//   Filter = 4.2 MHz BW centered at 3.0 MHz IF
//   Output = 2-bit sign/magnitude, I only
//
// Verified register values taken from pocketgnss.c test firmware.
//----------------------------------------------------------------------

#include "HWCtrl.h"
#include "PlatformCtrl.h"
#include "FreeRTOS.h"
#include "xscugic.h"
#include "xspips.h"
#include "xil_io.h"
#include "xparameters.h"

// --------------- GNSS baseband address ---------------
// Match the base address in Vivado IP Integrator Address Editor.
#define GNSS_BASE_ADDR  0x43C00000UL

// PL-to-PS interrupt: IRQ_F2P[0] = GIC shared peripheral interrupt 61.
// Verify in your Vivado block design (F2P[0] maps to GIC ID 61 on Zynq).
#define GNSS_IRQ_ID     61

// --------------- MAX2771 SPI ---------------
// PS SPI0 device ID (generated by Vivado / Vitis in xparameters.h).
#define MAX2771_SPI_ID  XPAR_XSPIPS_0_DEVICE_ID

// SPI clock prescaler: APB clock / prescaler value.
// With APB = 100 MHz, XSPIPS_CLK_PRESCALE_16 -> 6.25 MHz SCLK.
// MAX2771 supports up to 10 MHz SCLK.
#define MAX2771_SPI_PRESCALER  XSPIPS_CLK_PRESCALE_16

// --------------- MAX2771 register addresses (0-10) ---------------
#define MAX2771_REG_CONF1    0x0
#define MAX2771_REG_CONF2    0x1
#define MAX2771_REG_CONF3    0x2
#define MAX2771_REG_PLLCONF  0x3
#define MAX2771_REG_DIV      0x4
#define MAX2771_REG_FDIV     0x5
#define MAX2771_REG_STRM     0x6
#define MAX2771_REG_CLK      0x7
#define MAX2771_REG_TEST1    0x8
#define MAX2771_REG_TEST2    0x9
#define MAX2771_REG_TEST3    0xA

// --------------- MAX2771 register values for GPS L1CA ---------------
// Measured configuration (pocketgnss.c, chip A, 24 MHz crystal):
//   F_LO  = 1572.420 MHz  (3 MHz low-side of GPS L1 1575.42 MHz)
//   F_ADC = 12.000 MHz    (CLKOUT output rate)
//   F_IF  = 3.0 MHz
//   BW    = 4.2 MHz
//   Mode  = I only, 2-bit sign/magnitude output
// -----------------------------------------------------------------------
#define MAX2771_CONF1_VAL    0xA2241BD7UL
#define MAX2771_CONF2_VAL    0x20550288UL
#define MAX2771_CONF3_VAL    0x0E8F21D0UL
#define MAX2771_PLLCONF_VAL  0x49888008UL
#define MAX2771_DIV_VAL      0x0CCBEC80UL
#define MAX2771_FDIV_VAL     0x00000070UL
#define MAX2771_STRM_VAL     0x08000000UL
#define MAX2771_CLK_VAL      0x00000000UL
#define MAX2771_TEST1_VAL    0x01E0F281UL
#define MAX2771_TEST2_VAL    0x00000002UL
#define MAX2771_TEST3_VAL    0x00000004UL

// FreeRTOS: GIC instance is initialised by the FreeRTOS port startup code.
// Do NOT reinitialise it here; just attach to the existing instance.
extern XScuGic xInterruptController;

static XSpiPs    spi_inst;
static DebugFunction DebugFunc = NULL;

// ----------------------------------------------------------------
// Internal: write one MAX2771 register over PS SPI0.
// 48-bit transaction: 16-bit header (MSB first) + 32-bit data.
//   Header byte 0: upper 8 bits of 12-bit address (0x00 for reg 0-10)
//   Header byte 1: lower 4 bits of address in [7:4], R/W=0, pad=000
//   Bytes 2-5:     32-bit register value, MSB first
// ----------------------------------------------------------------
static void max2771_write_reg(u8 reg_addr, u32 data)
{
    u8 tx[6];
    tx[0] = 0x00U;
    tx[1] = (u8)((reg_addr & 0x0FU) << 4);   // addr[3:0] in [7:4]; R/W=0, pad=000
    tx[2] = (u8)(data >> 24);
    tx[3] = (u8)(data >> 16);
    tx[4] = (u8)(data >>  8);
    tx[5] = (u8)(data      );

    XSpiPs_SetSlaveSelect(&spi_inst, 0x0EU);  // assert SS0 (active-low bit mask)
    XSpiPs_PolledTransfer(&spi_inst, tx, NULL, 6);
    XSpiPs_SetSlaveSelect(&spi_inst, 0x0FU);  // deassert all SS
}

// ----------------------------------------------------------------
// Configure MAX2771 chip A for GPS L1CA reception.
// Registers written in the order: PLL first, then analog, then output.
// ----------------------------------------------------------------
static void max2771_init_gps_l1(void)
{
    max2771_write_reg(MAX2771_REG_PLLCONF, MAX2771_PLLCONF_VAL);
    max2771_write_reg(MAX2771_REG_DIV,     MAX2771_DIV_VAL    );
    max2771_write_reg(MAX2771_REG_FDIV,    MAX2771_FDIV_VAL   );
    max2771_write_reg(MAX2771_REG_CLK,     MAX2771_CLK_VAL    );
    max2771_write_reg(MAX2771_REG_CONF3,   MAX2771_CONF3_VAL  );
    max2771_write_reg(MAX2771_REG_CONF2,   MAX2771_CONF2_VAL  );
    max2771_write_reg(MAX2771_REG_CONF1,   MAX2771_CONF1_VAL  );
    max2771_write_reg(MAX2771_REG_STRM,    MAX2771_STRM_VAL   );
    max2771_write_reg(MAX2771_REG_TEST1,   MAX2771_TEST1_VAL  );
    max2771_write_reg(MAX2771_REG_TEST2,   MAX2771_TEST2_VAL  );
    max2771_write_reg(MAX2771_REG_TEST3,   MAX2771_TEST3_VAL  );
}

// ================================================================
// Public API (implements HWCtrl.h interface)
// ================================================================

// FreeRTOS-aware ISR attachment.
// The GIC is already initialised by the FreeRTOS port (xInterruptController).
// Do not re-initialise it here or register the top-level exception handler —
// FreeRTOS owns that.
void AttachBasebandISR(InterruptFunction ISR)
{
    XScuGic_Connect(&xInterruptController, GNSS_IRQ_ID,
                    (Xil_InterruptHandler)ISR, NULL);
    XScuGic_Enable(&xInterruptController, GNSS_IRQ_ID);
}

void AttachDebugFunc(DebugFunction Function)
{
    DebugFunc = Function;
}

// Address is DWORD offset (as used throughout gnss_top firmware).
U32 GetRegValue(int Address)
{
    return Xil_In32(GNSS_BASE_ADDR + ((u32)Address << 2));
}

void SetRegValue(int Address, U32 Value)
{
    Xil_Out32(GNSS_BASE_ADDR + ((u32)Address << 2), Value);
}

void LoadMemory(U32 *DestAddr, U32 *BasebandAddr, int Size)
{
    int i;
    for (i = 0; i < Size; i += 4)
        DestAddr[i >> 2] = Xil_In32(GNSS_BASE_ADDR + (u32)BasebandAddr + i);
}

void SaveMemory(U32 *BasebandAddr, U32 *SrcAddr, int Size)
{
    int i;
    for (i = 0; i < Size; i += 4)
        Xil_Out32(GNSS_BASE_ADDR + (u32)BasebandAddr + i, SrcAddr[i >> 2]);
}

void SetInputFile(char *FileName) {}

// Initialise PS SPI0 and configure MAX2771 chip A for GPS L1CA.
// Call once during system startup before enabling the GNSS baseband.
void EnableRF(void)
{
    XSpiPs_Config *spi_cfg;
    int status;

    spi_cfg = XSpiPs_LookupConfig(MAX2771_SPI_ID);
    if (!spi_cfg) return;

    status = XSpiPs_CfgInitialize(&spi_inst, spi_cfg, spi_cfg->BaseAddress);
    if (status != XST_SUCCESS) return;

    XSpiPs_Reset(&spi_inst);

    // Master mode, manual CS, CPOL=0 CPHA=0 (Mode 0), 8-bit words
    XSpiPs_SetOptions(&spi_inst,
        XSPIPS_MASTER_OPTION        |
        XSPIPS_FORCE_SSELECT_OPTION
    );
    XSpiPs_SetClkPrescaler(&spi_inst, MAX2771_SPI_PRESCALER);

    // Deassert all chip selects initially
    XSpiPs_SetSlaveSelect(&spi_inst, 0x0FU);

    max2771_init_gps_l1();
}
