//----------------------------------------------------------------------
// xilinx_rom_wrapper.v:
//   Xilinx FPGA ROM wrappers using xpm_memory_sprom.
//   Include this file INSTEAD OF backend_wrapper/mem_wrapper.v's ROM
//   sections when targeting Xilinx devices.
//   (The RAM wrappers in mem_wrapper.v are kept as-is; Vivado infers
//   them as RAMB18/RAMB36 automatically from the behavioral spram model.)
//
//   Before synthesis, place the three .mem files generated by
//   tools/gen_rom_init.py so Vivado can find them:
//     b1c_legendre.mem   (640 x 16-bit)
//     l1c_legendre.mem   (640 x 16-bit)
//     memory_code.mem    (12800 x 32-bit)
//
//   Recommended: copy the .mem files into the Vivado project directory
//   (the directory containing the .xpr file), or set an absolute path
//   in the MEMORY_INIT_FILE parameter below.
//
//   If you prefer Block Memory Generator IP over XPM:
//     1. In Vivado IP Catalog, create a Block Memory Generator with:
//          Port A Width = 16 (or 32), Depth = 640 (or 12800),
//          Enable Port Type = "Always Enabled", Load Init File = <coe>
//     2. Name the IP "b1c_legendre_rom", "l1c_legendre_rom",
//        "memory_code_rom" and delete this file from the project.
//----------------------------------------------------------------------

// ------------------------------------------------------------------
// BDS B1C Legendre ROM  (640 x 16-bit)
// ------------------------------------------------------------------
module b1c_legendre_rom_640x16_wrapper
(
    input         clk,
    input         rd,
    input  [9:0]  addr,
    output [15:0] rdata
);

xpm_memory_sprom #(
    .ADDR_WIDTH_A       (10),
    .ECC_MODE           ("no_ecc"),
    .MEMORY_INIT_FILE   ("b1c_legendre.mem"),
    .MEMORY_INIT_PARAM  (""),
    .MEMORY_OPTIMIZATION("true"),
    .MEMORY_PRIMITIVE   ("block"),
    .MEMORY_SIZE        (640 * 16),
    .MESSAGE_CONTROL    (0),
    .READ_DATA_WIDTH_A  (16),
    .READ_LATENCY_A     (1),
    .READ_RESET_VALUE_A ("0"),
    .RST_MODE_A         ("SYNC"),
    .USE_MEM_INIT       (1),
    .WAKEUP_TIME        ("disable_sleep")
) u_rom (
    .clka   (clk   ),
    .addra  (addr  ),
    .douta  (rdata ),
    .ena    (rd    ),
    .rsta   (1'b0  ),
    .regcea (1'b1  ),
    .sleep  (1'b0  )
);

endmodule


// ------------------------------------------------------------------
// GPS/QZSS L1C Legendre ROM  (640 x 16-bit)
// ------------------------------------------------------------------
module l1c_legendre_rom_640x16_wrapper
(
    input         clk,
    input         rd,
    input  [9:0]  addr,
    output [15:0] rdata
);

xpm_memory_sprom #(
    .ADDR_WIDTH_A       (10),
    .ECC_MODE           ("no_ecc"),
    .MEMORY_INIT_FILE   ("l1c_legendre.mem"),
    .MEMORY_INIT_PARAM  (""),
    .MEMORY_OPTIMIZATION("true"),
    .MEMORY_PRIMITIVE   ("block"),
    .MEMORY_SIZE        (640 * 16),
    .MESSAGE_CONTROL    (0),
    .READ_DATA_WIDTH_A  (16),
    .READ_LATENCY_A     (1),
    .READ_RESET_VALUE_A ("0"),
    .RST_MODE_A         ("SYNC"),
    .USE_MEM_INIT       (1),
    .WAKEUP_TIME        ("disable_sleep")
) u_rom (
    .clka   (clk   ),
    .addra  (addr  ),
    .douta  (rdata ),
    .ena    (rd    ),
    .rsta   (1'b0  ),
    .regcea (1'b1  ),
    .sleep  (1'b0  )
);

endmodule


// ------------------------------------------------------------------
// Galileo E1 / BDS B1C memory code ROM  (12800 x 32-bit)
// ------------------------------------------------------------------
module memory_code_rom_12800x32_wrapper
(
    input          clk,
    input          rd,
    input  [13:0]  addr,
    output [31:0]  rdata
);

xpm_memory_sprom #(
    .ADDR_WIDTH_A       (14),
    .ECC_MODE           ("no_ecc"),
    .MEMORY_INIT_FILE   ("memory_code.mem"),
    .MEMORY_INIT_PARAM  (""),
    .MEMORY_OPTIMIZATION("true"),
    .MEMORY_PRIMITIVE   ("block"),
    .MEMORY_SIZE        (12800 * 32),
    .MESSAGE_CONTROL    (0),
    .READ_DATA_WIDTH_A  (32),
    .READ_LATENCY_A     (1),
    .READ_RESET_VALUE_A ("0"),
    .RST_MODE_A         ("SYNC"),
    .USE_MEM_INIT       (1),
    .WAKEUP_TIME        ("disable_sleep")
) u_rom (
    .clka   (clk   ),
    .addra  (addr  ),
    .douta  (rdata ),
    .ena    (rd    ),
    .rsta   (1'b0  ),
    .regcea (1'b1  ),
    .sleep  (1'b0  )
);

endmodule
